# Site settings
# title: homepage
# description: homepage
# baseurl: "" # プロジェクトのベースURL。リポジトリ名の前にスラッシュをつける例: /repo-name
# url: "https://c0b22043dc.github.io" # あなたのGitHub Pages URL

# Build settings
theme: jekyll-theme-cayman

# Social media settings (optional)
# twitter_username: あなたのTwitterユーザー名
# github_username: あなたのGitHubユーザー名

# Google Analytics (optional)
# google_analytics: UA-XXXXXXXX-X
